### ISSUE TITLE
Add copy button to code blocks

### ISSUE THREAD

**Issue by swvanbuuren** [swvanbuuren/mlpyqtgraph#8]
It would be nice to have copy buttons on each code block.

In order to have this, add:

```yaml
theme:
  features:
  - content.code.copy
```

to `mkdocs.yml`.
